---
- name: Install firewalld by using hostscope variable
  hosts: appserver
  tasks:
    - name: install firewalld
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...
