---
- name: Installing of jenkins and required softwares
  hosts: jenkinsserver 
  tasks:
     - name: Install reqiured s/w's
       apt: 
          name: "{{item.a}}"
          state: "{{item.b}}"
          update_cache: "{{item.c}}"
       with_items: 
          - {a: openjdk-11-jdk,b: present,c: yes}
          - {a: git,b: present,c: no}
          - {a: maven,b: present,c: no}
     - name: downloading jenlins.war
       get_url:
          url: https://get.jenkins.io/war-stable/2.375.2/jenkins.war
          dest: /home/ubuntu
- name: Installing of tomcat9,tomcat9-admin and required softwares
  hosts: servers
  tasks:
     - name: Install tomcat9 tomcat9-admin
       apt:
          name: "{{item.a}}"
          state: "{{item.b}}"
          update_cache: "{{item.c}}"
       with_items:
          - {a: tomcat9,b: present,c: yes}
          - {a: tomcat9-admin,b: present,c: no}
     - name: editing tomcat-users.xml file
       copy: 
          src: tomcat-users.xml
          dest: /etc/tomcat9
       notify: restart tomcat9
  handlers: 
      - name: restart tomcat9
        service:
           name: tomcat9
           state: restarted     
...
     
 

