---
- name: Installing softwares
  hosts: all
  vars: 
    - a: tomcat9
    - b: present
    - c: yes
  tasks:
    - name: install
      apt:
         name: "{{a}}"
         state: "{{b}}"
         update_cache: "{{c}}"
...
